# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gmprincep/gitfiles/bluenet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gmprincep/gitfiles/bluenet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gmprincep/gitfiles/bluenet/CMakeFiles /home/gmprincep/gitfiles/bluenet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gmprincep/gitfiles/bluenet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nrfconnect_core_setup

# Build rule for target.
nrfconnect_core_setup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nrfconnect_core_setup
.PHONY : nrfconnect_core_setup

# fast build rule for target.
nrfconnect_core_setup/fast:
	$(MAKE) -f CMakeFiles/nrfconnect_core_setup.dir/build.make CMakeFiles/nrfconnect_core_setup.dir/build
.PHONY : nrfconnect_core_setup/fast

#=============================================================================
# Target rules for targets named nrfconnect_core

# Build rule for target.
nrfconnect_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nrfconnect_core
.PHONY : nrfconnect_core

# fast build rule for target.
nrfconnect_core/fast:
	$(MAKE) -f CMakeFiles/nrfconnect_core.dir/build.make CMakeFiles/nrfconnect_core.dir/build
.PHONY : nrfconnect_core/fast

#=============================================================================
# Target rules for targets named list_jlinks

# Build rule for target.
list_jlinks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 list_jlinks
.PHONY : list_jlinks

# fast build rule for target.
list_jlinks/fast:
	$(MAKE) -f CMakeFiles/list_jlinks.dir/build.make CMakeFiles/list_jlinks.dir/build
.PHONY : list_jlinks/fast

#=============================================================================
# Target rules for targets named write_bootloader

# Build rule for target.
write_bootloader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 write_bootloader
.PHONY : write_bootloader

# fast build rule for target.
write_bootloader/fast:
	$(MAKE) -f CMakeFiles/write_bootloader.dir/build.make CMakeFiles/write_bootloader.dir/build
.PHONY : write_bootloader/fast

#=============================================================================
# Target rules for targets named nrfjprog

# Build rule for target.
nrfjprog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nrfjprog
.PHONY : nrfjprog

# fast build rule for target.
nrfjprog/fast:
	$(MAKE) -f CMakeFiles/nrfjprog.dir/build.make CMakeFiles/nrfjprog.dir/build
.PHONY : nrfjprog/fast

#=============================================================================
# Target rules for targets named jlink

# Build rule for target.
jlink: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jlink
.PHONY : jlink

# fast build rule for target.
jlink/fast:
	$(MAKE) -f CMakeFiles/jlink.dir/build.make CMakeFiles/jlink.dir/build
.PHONY : jlink/fast

#=============================================================================
# Target rules for targets named gcc_arm_none_eabi

# Build rule for target.
gcc_arm_none_eabi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gcc_arm_none_eabi
.PHONY : gcc_arm_none_eabi

# fast build rule for target.
gcc_arm_none_eabi/fast:
	$(MAKE) -f CMakeFiles/gcc_arm_none_eabi.dir/build.make CMakeFiles/gcc_arm_none_eabi.dir/build
.PHONY : gcc_arm_none_eabi/fast

#=============================================================================
# Target rules for targets named nordic_sdk

# Build rule for target.
nordic_sdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nordic_sdk
.PHONY : nordic_sdk

# fast build rule for target.
nordic_sdk/fast:
	$(MAKE) -f CMakeFiles/nordic_sdk.dir/build.make CMakeFiles/nordic_sdk.dir/build
.PHONY : nordic_sdk/fast

#=============================================================================
# Target rules for targets named nordic_mesh_sdk

# Build rule for target.
nordic_mesh_sdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nordic_mesh_sdk
.PHONY : nordic_mesh_sdk

# fast build rule for target.
nordic_mesh_sdk/fast:
	$(MAKE) -f CMakeFiles/nordic_mesh_sdk.dir/build.make CMakeFiles/nordic_mesh_sdk.dir/build
.PHONY : nordic_mesh_sdk/fast

#=============================================================================
# Target rules for targets named micro_eec

# Build rule for target.
micro_eec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 micro_eec
.PHONY : micro_eec

# fast build rule for target.
micro_eec/fast:
	$(MAKE) -f CMakeFiles/micro_eec.dir/build.make CMakeFiles/micro_eec.dir/build
.PHONY : micro_eec/fast

#=============================================================================
# Target rules for targets named read_softdevice_version

# Build rule for target.
read_softdevice_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read_softdevice_version
.PHONY : read_softdevice_version

# fast build rule for target.
read_softdevice_version/fast:
	$(MAKE) -f CMakeFiles/read_softdevice_version.dir/build.make CMakeFiles/read_softdevice_version.dir/build
.PHONY : read_softdevice_version/fast

#=============================================================================
# Target rules for targets named nrfconnect_programmer

# Build rule for target.
nrfconnect_programmer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nrfconnect_programmer
.PHONY : nrfconnect_programmer

# fast build rule for target.
nrfconnect_programmer/fast:
	$(MAKE) -f CMakeFiles/nrfconnect_programmer.dir/build.make CMakeFiles/nrfconnect_programmer.dir/build
.PHONY : nrfconnect_programmer/fast

#=============================================================================
# Target rules for targets named nrfutil

# Build rule for target.
nrfutil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nrfutil
.PHONY : nrfutil

# fast build rule for target.
nrfutil/fast:
	$(MAKE) -f CMakeFiles/nrfutil.dir/build.make CMakeFiles/nrfutil.dir/build
.PHONY : nrfutil/fast

#=============================================================================
# Target rules for targets named erase

# Build rule for target.
erase: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 erase
.PHONY : erase

# fast build rule for target.
erase/fast:
	$(MAKE) -f CMakeFiles/erase.dir/build.make CMakeFiles/erase.dir/build
.PHONY : erase/fast

#=============================================================================
# Target rules for targets named reset

# Build rule for target.
reset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reset
.PHONY : reset

# fast build rule for target.
reset/fast:
	$(MAKE) -f CMakeFiles/reset.dir/build.make CMakeFiles/reset.dir/build
.PHONY : reset/fast

#=============================================================================
# Target rules for targets named default

# Build rule for target.
default: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 default
.PHONY : default

# fast build rule for target.
default/fast:
	$(MAKE) -f CMakeFiles/default.dir/build.make CMakeFiles/default.dir/build
.PHONY : default/fast

#=============================================================================
# Target rules for targets named debug_application

# Build rule for target.
debug_application: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug_application
.PHONY : debug_application

# fast build rule for target.
debug_application/fast:
	$(MAKE) -f CMakeFiles/debug_application.dir/build.make CMakeFiles/debug_application.dir/build
.PHONY : debug_application/fast

#=============================================================================
# Target rules for targets named bluenet

# Build rule for target.
bluenet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bluenet
.PHONY : bluenet

# fast build rule for target.
bluenet/fast:
	$(MAKE) -f CMakeFiles/bluenet.dir/build.make CMakeFiles/bluenet.dir/build
.PHONY : bluenet/fast

#=============================================================================
# Target rules for targets named write_board_version

# Build rule for target.
write_board_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 write_board_version
.PHONY : write_board_version

# fast build rule for target.
write_board_version/fast:
	$(MAKE) -f CMakeFiles/write_board_version.dir/build.make CMakeFiles/write_board_version.dir/build
.PHONY : write_board_version/fast

#=============================================================================
# Target rules for targets named write_softdevice

# Build rule for target.
write_softdevice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 write_softdevice
.PHONY : write_softdevice

# fast build rule for target.
write_softdevice/fast:
	$(MAKE) -f CMakeFiles/write_softdevice.dir/build.make CMakeFiles/write_softdevice.dir/build
.PHONY : write_softdevice/fast

#=============================================================================
# Target rules for targets named write_application

# Build rule for target.
write_application: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 write_application
.PHONY : write_application

# fast build rule for target.
write_application/fast:
	$(MAKE) -f CMakeFiles/write_application.dir/build.make CMakeFiles/write_application.dir/build
.PHONY : write_application/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... nrfconnect_core_setup"
	@echo "... nrfconnect_core"
	@echo "... list_jlinks"
	@echo "... write_bootloader"
	@echo "... nrfjprog"
	@echo "... jlink"
	@echo "... gcc_arm_none_eabi"
	@echo "... nordic_sdk"
	@echo "... nordic_mesh_sdk"
	@echo "... micro_eec"
	@echo "... read_softdevice_version"
	@echo "... nrfconnect_programmer"
	@echo "... nrfutil"
	@echo "... erase"
	@echo "... reset"
	@echo "... rebuild_cache"
	@echo "... default"
	@echo "... debug_application"
	@echo "... bluenet"
	@echo "... write_board_version"
	@echo "... write_softdevice"
	@echo "... write_application"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

